### CSRF

GET http://localhost:8000/sanctum/csrf-cookie
Accept: application/json

### LOGIN

POST http://localhost:8000/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "Admin@123456"
}

### Get Me
GET http://localhost:8000/api/me

### Logout
POST http://localhost:8000/api/logout

### ==========================================
### ADMIN DASHBOARD
### ==========================================

GET http://localhost:8000/api/admin/dashboard
Accept: application/json